version: '3.8'

services:
  crud-vti-fe:
    build:
      context: ./crud-vti-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - app-network

  crud-vti-be:
    build:
      context: ./crud-vti-be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=products
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=products
    depends_on:
      - products
    networks:
      - app-network

  products:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
